[package]
name = "tauri-app"
version = "1.1.1" # Esta es la versión de tu app, no de Tauri
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
# ELIMINADO: features = ["updater"] ya no existe aquí en v2
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
# Actualizamos a "2" para que Cargo elija la más compatible con tus paquetes de NPM
tauri-plugin-updater = "2" 
tauri-plugin-process = "2" 
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio-rustls"] }
chrono = "0.4"
open = "5.0"

