# ===========================
# 🔍 Configuración de análisis SonarQube
# Proyecto: Alta Médicos Automatización QA
# ===========================

# 🧩 Identificación del proyecto
sonar.projectKey=AltaMedicos
sonar.projectName=AltaMedicos-AutomatizacionQA
sonar.projectVersion=1.0

# 📂 Rutas de código fuente
sonar.sources=src
sonar.language=ts
sonar.sourceEncoding=UTF-8

# 📦 Exclusiones de análisis (archivos o carpetas que no aportan al análisis)
sonar.exclusions=**/node_modules/**,**/Evidencias/**,**/archivos/**,**/dist/**,**/test-results/**,**/playwright-report/**,**/*.spec.ts

# 🧪 Directorio de pruebas (opcional si quieres ver las pruebas separadas)
sonar.tests=src/tests

# ⚙️ Configuración de TypeScript (para Sonar >= 9)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

# 🌐 Conexión a SonarQube local
sonar.host.url=http://localhost:9010

# 🔑 Token de autenticación (reemplázalo con el tuyo)
sonar.token=sqa_c2ac7e9461e3d699afa667df99e8c09f5e15d60d

# 🧠 Información opcional para mejor clasificación en Sonar
sonar.projectDescription=Automatización QA del flujo Alta Médicos, implementada con Playwright + TypeScript bajo patrón POM.
sonar.organization=local
sonar.links.homepage=http://localhost:9010/dashboard?id=AltaMedicos
sonar.links.scm=https://github.com/
sonar.links.issue=https://github.com/issues
